// SPDX-License-Identifier: GPL-3.0-or-later
// src/inventory/data.ts — Static Objekt catalogue with baked image asset paths.

import type { MemberInfo, ObjektCard } from "./types.ts";

export const MEMBERS: MemberInfo[] = [
  {
    "id": "heejin",
    "name": "HeeJin",
    "koreanName": "희진",
    "color": "#ec4899",
    "badgeBg": "#fdf2f8",
    "symbol": "🐰",
    "role": "ALL-ROUNDER"
  },
  {
    "id": "haseul",
    "name": "HaSeul",
    "koreanName": "하슬",
    "color": "#10b981",
    "badgeBg": "#ecfdf5",
    "symbol": "🕊️",
    "role": "LEADER • VOCAL"
  },
  {
    "id": "kimlip",
    "name": "Kim Lip",
    "koreanName": "김립",
    "color": "#ef4444",
    "badgeBg": "#fef2f2",
    "symbol": "🦉",
    "role": "LEAD VOCAL"
  },
  {
    "id": "jinsoul",
    "name": "JinSoul",
    "koreanName": "진솔",
    "color": "#3b82f6",
    "badgeBg": "#eff6ff",
    "symbol": "🐟",
    "role": "MAIN RAPPER • VOCAL"
  },
  {
    "id": "choerry",
    "name": "Choerry",
    "koreanName": "최리",
    "color": "#8b5cf6",
    "badgeBg": "#f5f3ff",
    "symbol": "🦇",
    "role": "LEAD DANCER • VOCAL"
  }
];

export const OBJEKTS: ObjektCard[] = [
  {
    "id": "heejin-01",
    "artist": "ARTMS",
    "member": "HeeJin",
    "memberId": "heejin",
    "season": "Atom01",
    "class": "First",
    "type": "Digital",
    "number": "#117Z",
    "information": "Sold on the COSMO app shop. Gifted throughout various events on Discord.",
    "imageFront": "cards/heejin_atom01_117.png",
    "imageBack": "cards/heejin_atom01_back.png",
    "tag": "ALL-ROUNDER"
  },
  {
    "id": "heejin-01",
    "artist": "ARTMS",
    "member": "HeeJin",
    "memberId": "heejin",
    "season": "Atom01",
    "class": "First",
    "type": "Digital",
    "number": "#118Z",
    "information": "Sold on the COSMO app shop. Gifted throughout various events on Discord.",
    "imageFront": "cards/heejin_atom01_118.png",
    "imageBack": "cards/heejin_atom01_back.png",
    "tag": "ALL-ROUNDER"
  },
  {
    "id": "heejin-01",
    "artist": "ARTMS",
    "member": "HeeJin",
    "memberId": "heejin",
    "season": "Atom01",
    "class": "First",
    "type": "Digital",
    "number": "#119Z",
    "information": "Sold on the COSMO app shop. Gifted throughout various events on Discord.",
    "imageFront": "cards/heejin_atom01_119.png",
    "imageBack": "cards/heejin_atom01_back.png",
    "tag": "ALL-ROUNDER"
  },
  {
    "id": "heejin-01",
    "artist": "ARTMS",
    "member": "HeeJin",
    "memberId": "heejin",
    "season": "Atom01",
    "class": "First",
    "type": "Digital",
    "number": "#120Z",
    "information": "Sold on the COSMO app shop. Gifted throughout various events on Discord.",
    "imageFront": "cards/heejin_atom01_120.png",
    "imageBack": "cards/heejin_atom01_back.png",
    "tag": "ALL-ROUNDER"
  },
  {
    "id": "heejin-01",
    "artist": "ARTMS",
    "member": "HeeJin",
    "memberId": "heejin",
    "season": "Atom01",
    "class": "Special",
    "type": "Digital",
    "number": "#205Z",
    "information": "Gifted for completing a grid of 117-120 First Class Objekts on COSMO.",
    "imageFront": "cards/heejin_atom01_205.png",
    "imageBack": "cards/heejin_atom01_back_sp.png",
    "tag": "ALL-ROUNDER"
  },
  {
    "id": "heejin-01",
    "artist": "ARTMS",
    "member": "HeeJin",
    "memberId": "heejin",
    "season": "Atom01",
    "class": "Special",
    "type": "Digital",
    "number": "#206Z",
    "information": "Gifted for completing a grid of 117-120 First Class Objekts on COSMO.",
    "imageFront": "cards/heejin_atom01_206.png",
    "imageBack": "cards/heejin_atom01_back_sp.png",
    "tag": "ALL-ROUNDER"
  },
  {
    "id": "haseul-01",
    "artist": "ARTMS",
    "member": "HaSeul",
    "memberId": "haseul",
    "season": "Atom01",
    "class": "First",
    "type": "Digital",
    "number": "#117Z",
    "information": "Sold on the COSMO app shop. Gifted throughout various events on Discord.",
    "imageFront": "cards/haseul_atom01_117.png",
    "imageBack": "cards/haseul_atom01_back.png",
    "tag": "LEADER • VOCAL"
  },
  {
    "id": "haseul-01",
    "artist": "ARTMS",
    "member": "HaSeul",
    "memberId": "haseul",
    "season": "Atom01",
    "class": "First",
    "type": "Digital",
    "number": "#118Z",
    "information": "Sold on the COSMO app shop. Gifted throughout various events on Discord.",
    "imageFront": "cards/haseul_atom01_118.png",
    "imageBack": "cards/haseul_atom01_back.png",
    "tag": "LEADER • VOCAL"
  },
  {
    "id": "haseul-01",
    "artist": "ARTMS",
    "member": "HaSeul",
    "memberId": "haseul",
    "season": "Atom01",
    "class": "First",
    "type": "Digital",
    "number": "#119Z",
    "information": "Sold on the COSMO app shop. Gifted throughout various events on Discord.",
    "imageFront": "cards/haseul_atom01_119.png",
    "imageBack": "cards/haseul_atom01_back.png",
    "tag": "LEADER • VOCAL"
  },
  {
    "id": "haseul-01",
    "artist": "ARTMS",
    "member": "HaSeul",
    "memberId": "haseul",
    "season": "Atom01",
    "class": "First",
    "type": "Digital",
    "number": "#120Z",
    "information": "Sold on the COSMO app shop. Gifted throughout various events on Discord.",
    "imageFront": "cards/haseul_atom01_120.png",
    "imageBack": "cards/haseul_atom01_back.png",
    "tag": "LEADER • VOCAL"
  },
  {
    "id": "haseul-01",
    "artist": "ARTMS",
    "member": "HaSeul",
    "memberId": "haseul",
    "season": "Atom01",
    "class": "Special",
    "type": "Digital",
    "number": "#205Z",
    "information": "Gifted for completing a grid of 117-120 First Class Objekts on COSMO.",
    "imageFront": "cards/haseul_atom01_205.png",
    "imageBack": "cards/haseul_atom01_back_sp.png",
    "tag": "LEADER • VOCAL"
  },
  {
    "id": "haseul-01",
    "artist": "ARTMS",
    "member": "HaSeul",
    "memberId": "haseul",
    "season": "Atom01",
    "class": "Special",
    "type": "Digital",
    "number": "#206Z",
    "information": "Gifted for completing a grid of 117-120 First Class Objekts on COSMO.",
    "imageFront": "cards/haseul_atom01_206.png",
    "imageBack": "cards/haseul_atom01_back_sp.png",
    "tag": "LEADER • VOCAL"
  },
  {
    "id": "kimlip-01",
    "artist": "ARTMS",
    "member": "Kim Lip",
    "memberId": "kimlip",
    "season": "Atom01",
    "class": "First",
    "type": "Digital",
    "number": "#117Z",
    "information": "Sold on the COSMO app shop. Gifted throughout various events on Discord.",
    "imageFront": "cards/kimlip_atom01_117.png",
    "imageBack": "cards/kimlip_atom01_back.png",
    "tag": "LEAD VOCAL"
  },
  {
    "id": "kimlip-01",
    "artist": "ARTMS",
    "member": "Kim Lip",
    "memberId": "kimlip",
    "season": "Atom01",
    "class": "First",
    "type": "Digital",
    "number": "#118Z",
    "information": "Sold on the COSMO app shop. Gifted throughout various events on Discord.",
    "imageFront": "cards/kimlip_atom01_118.png",
    "imageBack": "cards/kimlip_atom01_back.png",
    "tag": "LEAD VOCAL"
  },
  {
    "id": "kimlip-01",
    "artist": "ARTMS",
    "member": "Kim Lip",
    "memberId": "kimlip",
    "season": "Atom01",
    "class": "First",
    "type": "Digital",
    "number": "#119Z",
    "information": "Sold on the COSMO app shop. Gifted throughout various events on Discord.",
    "imageFront": "cards/kimlip_atom01_119.png",
    "imageBack": "cards/kimlip_atom01_back.png",
    "tag": "LEAD VOCAL"
  },
  {
    "id": "kimlip-01",
    "artist": "ARTMS",
    "member": "Kim Lip",
    "memberId": "kimlip",
    "season": "Atom01",
    "class": "First",
    "type": "Digital",
    "number": "#120Z",
    "information": "Sold on the COSMO app shop. Gifted throughout various events on Discord.",
    "imageFront": "cards/kimlip_atom01_120.png",
    "imageBack": "cards/kimlip_atom01_back.png",
    "tag": "LEAD VOCAL"
  },
  {
    "id": "kimlip-01",
    "artist": "ARTMS",
    "member": "Kim Lip",
    "memberId": "kimlip",
    "season": "Atom01",
    "class": "Special",
    "type": "Digital",
    "number": "#205Z",
    "information": "Gifted for completing a grid of 117-120 First Class Objekts on COSMO.",
    "imageFront": "cards/kimlip_atom01_205.png",
    "imageBack": "cards/kimlip_atom01_back_sp.png",
    "tag": "LEAD VOCAL"
  },
  {
    "id": "kimlip-01",
    "artist": "ARTMS",
    "member": "Kim Lip",
    "memberId": "kimlip",
    "season": "Atom01",
    "class": "Special",
    "type": "Digital",
    "number": "#206Z",
    "information": "Gifted for completing a grid of 117-120 First Class Objekts on COSMO.",
    "imageFront": "cards/kimlip_atom01_206.png",
    "imageBack": "cards/kimlip_atom01_back_sp.png",
    "tag": "LEAD VOCAL"
  },
  {
    "id": "jinsoul-01",
    "artist": "ARTMS",
    "member": "JinSoul",
    "memberId": "jinsoul",
    "season": "Atom01",
    "class": "First",
    "type": "Digital",
    "number": "#117Z",
    "information": "Sold on the COSMO app shop. Gifted throughout various events on Discord.",
    "imageFront": "cards/jinsoul_atom01_117.png",
    "imageBack": "cards/jinsoul_atom01_back.png",
    "tag": "MAIN RAPPER • VOCAL"
  },
  {
    "id": "jinsoul-01",
    "artist": "ARTMS",
    "member": "JinSoul",
    "memberId": "jinsoul",
    "season": "Atom01",
    "class": "First",
    "type": "Digital",
    "number": "#118Z",
    "information": "Sold on the COSMO app shop. Gifted throughout various events on Discord.",
    "imageFront": "cards/jinsoul_atom01_118.png",
    "imageBack": "cards/jinsoul_atom01_back.png",
    "tag": "MAIN RAPPER • VOCAL"
  },
  {
    "id": "jinsoul-01",
    "artist": "ARTMS",
    "member": "JinSoul",
    "memberId": "jinsoul",
    "season": "Atom01",
    "class": "First",
    "type": "Digital",
    "number": "#119Z",
    "information": "Sold on the COSMO app shop. Gifted throughout various events on Discord.",
    "imageFront": "cards/jinsoul_atom01_119.png",
    "imageBack": "cards/jinsoul_atom01_back.png",
    "tag": "MAIN RAPPER • VOCAL"
  },
  {
    "id": "jinsoul-01",
    "artist": "ARTMS",
    "member": "JinSoul",
    "memberId": "jinsoul",
    "season": "Atom01",
    "class": "First",
    "type": "Digital",
    "number": "#120Z",
    "information": "Sold on the COSMO app shop. Gifted throughout various events on Discord.",
    "imageFront": "cards/jinsoul_atom01_120.png",
    "imageBack": "cards/jinsoul_atom01_back.png",
    "tag": "MAIN RAPPER • VOCAL"
  },
  {
    "id": "jinsoul-01",
    "artist": "ARTMS",
    "member": "JinSoul",
    "memberId": "jinsoul",
    "season": "Atom01",
    "class": "Special",
    "type": "Digital",
    "number": "#205Z",
    "information": "Gifted for completing a grid of 117-120 First Class Objekts on COSMO.",
    "imageFront": "cards/jinsoul_atom01_205.png",
    "imageBack": "cards/jinsoul_atom01_back_sp.png",
    "tag": "MAIN RAPPER • VOCAL"
  },
  {
    "id": "jinsoul-01",
    "artist": "ARTMS",
    "member": "JinSoul",
    "memberId": "jinsoul",
    "season": "Atom01",
    "class": "Special",
    "type": "Digital",
    "number": "#206Z",
    "information": "Gifted for completing a grid of 117-120 First Class Objekts on COSMO.",
    "imageFront": "cards/jinsoul_atom01_206.png",
    "imageBack": "cards/jinsoul_atom01_back_sp.png",
    "tag": "MAIN RAPPER • VOCAL"
  },
  {
    "id": "choerry-01",
    "artist": "ARTMS",
    "member": "Choerry",
    "memberId": "choerry",
    "season": "Atom01",
    "class": "First",
    "type": "Digital",
    "number": "#117Z",
    "information": "Sold on the COSMO app shop. Gifted throughout various events on Discord.",
    "imageFront": "cards/choerry_atom01_117.png",
    "imageBack": "cards/choerry_atom01_back.png",
    "tag": "LEAD DANCER • VOCAL"
  },
  {
    "id": "choerry-01",
    "artist": "ARTMS",
    "member": "Choerry",
    "memberId": "choerry",
    "season": "Atom01",
    "class": "First",
    "type": "Digital",
    "number": "#118Z",
    "information": "Sold on the COSMO app shop. Gifted throughout various events on Discord.",
    "imageFront": "cards/choerry_atom01_118.png",
    "imageBack": "cards/choerry_atom01_back.png",
    "tag": "LEAD DANCER • VOCAL"
  },
  {
    "id": "choerry-01",
    "artist": "ARTMS",
    "member": "Choerry",
    "memberId": "choerry",
    "season": "Atom01",
    "class": "First",
    "type": "Digital",
    "number": "#119Z",
    "information": "Sold on the COSMO app shop. Gifted throughout various events on Discord.",
    "imageFront": "cards/choerry_atom01_119.png",
    "imageBack": "cards/choerry_atom01_back.png",
    "tag": "LEAD DANCER • VOCAL"
  },
  {
    "id": "choerry-01",
    "artist": "ARTMS",
    "member": "Choerry",
    "memberId": "choerry",
    "season": "Atom01",
    "class": "First",
    "type": "Digital",
    "number": "#120Z",
    "information": "Sold on the COSMO app shop. Gifted throughout various events on Discord.",
    "imageFront": "cards/choerry_atom01_120.png",
    "imageBack": "cards/choerry_atom01_back.png",
    "tag": "LEAD DANCER • VOCAL"
  },
  {
    "id": "choerry-01",
    "artist": "ARTMS",
    "member": "Choerry",
    "memberId": "choerry",
    "season": "Atom01",
    "class": "Special",
    "type": "Digital",
    "number": "#205Z",
    "information": "Gifted for completing a grid of 117-120 First Class Objekts on COSMO.",
    "imageFront": "cards/choerry_atom01_205.png",
    "imageBack": "cards/choerry_atom01_back_sp.png",
    "tag": "LEAD DANCER • VOCAL"
  },
  {
    "id": "choerry-01",
    "artist": "ARTMS",
    "member": "Choerry",
    "memberId": "choerry",
    "season": "Atom01",
    "class": "Special",
    "type": "Digital",
    "number": "#206Z",
    "information": "Gifted for completing a grid of 117-120 First Class Objekts on COSMO.",
    "imageFront": "cards/choerry_atom01_206.png",
    "imageBack": "cards/choerry_atom01_back_sp.png",
    "tag": "LEAD DANCER • VOCAL"
  }
];
